// Generated by NanoCSS CLI (v0.0.0)
import { nanocss } from 'nanocss'

export const { props, create, inline, styleSheet } = nanocss({
  hooks: [':hover'],
  debug: process.env.NODE_ENV !== 'production',
})
