// Generated by NanoCSS CLI (v0.0.2)
import { nanocss } from '@nanocss/nanocss'

export const { props, create, inline, defineVars, createTheme, styleSheet } =
  nanocss({
    hooks: [":hover"],
    debug: process.env.NODE_ENV !== 'production',
  })
