// Generated by NanoCSS CLI (v0.0.5)
import { nanocss } from '@nanocss/nanocss'

export const {
  props,
  create,
  inline,
  defineVars,
  createTheme,
  keyframes,
  styleSheet,
} = nanocss({
  hooks: [':hover'],
  debug: process.env.NODE_ENV !== 'production',
})
